name: Publish Python Package to github packages
on: push   
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install setuptools wheel twine

      - name: Build and Publish
        run: python setup.py sdist bdist_wheel

      - name: publish Package
        run: |
          twine upload --verbose --repository-url https://pypi.pkg.github.com/maup007/test-python dist/*
        env:
          TWINE_USERNAME: maup007
          TWINE_PASSWORD: ${{secrets.JAVA_TOKEN}}
